// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoT3ZDBXBO2hLFwh5jITS3AV-8etikZ9Q',
    appId: '1:519918791296:web:e4cdb5e30a604e6d625465',
    messagingSenderId: '519918791296',
    projectId: 'summer-app-a803e',
    authDomain: 'summer-app-a803e.firebaseapp.com',
    storageBucket: 'summer-app-a803e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxPcJraS2sduUL_yK7OKfExpCpAt3qhI',
    appId: '1:519918791296:android:f4947c6b344061f6625465',
    messagingSenderId: '519918791296',
    projectId: 'summer-app-a803e',
    storageBucket: 'summer-app-a803e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRLvN11M6ILc7a0S0pgx3Fs634BVCL08',
    appId: '1:519918791296:ios:f314f179be512755625465',
    messagingSenderId: '519918791296',
    projectId: 'summer-app-a803e',
    storageBucket: 'summer-app-a803e.appspot.com',
    iosBundleId: 'com.example.summerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRLvN11M6ILc7a0S0pgx3Fs634BVCL08',
    appId: '1:519918791296:ios:f314f179be512755625465',
    messagingSenderId: '519918791296',
    projectId: 'summer-app-a803e',
    storageBucket: 'summer-app-a803e.appspot.com',
    iosBundleId: 'com.example.summerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoT3ZDBXBO2hLFwh5jITS3AV-8etikZ9Q',
    appId: '1:519918791296:web:d69dd1bfc97aa757625465',
    messagingSenderId: '519918791296',
    projectId: 'summer-app-a803e',
    authDomain: 'summer-app-a803e.firebaseapp.com',
    storageBucket: 'summer-app-a803e.appspot.com',
  );
}
